#!/bin/bash

# Get the C file name from the environment variable
cfile=$CFILE

# Generate the output file name by replacing the extension with ".s"
sfile="${cfile%.*}.s"

# Compile the C file and generate the assembly code
gcc -S -masm=intel "$cfile" -o "$sfile"
